# Generated by Django 5.2.7 on 2025-10-20 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookshelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('FIC', 'Fiction'), ('NF', 'Non-Fiction'), ('SCI', 'Science Fiction'), ('FAN', 'Fantasy'), ('MYS', 'Mystery'), ('HOR', 'Horror/Thriller'), ('ROM', 'Romance'), ('AAA', 'Action & Adventure')], default='FIC', max_length=3)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)])),
            ],
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
